### ISSUE TITLE
vocab list 공유 요청

### ISSUE THREAD

**Issue by favorite-name** [MrBananaHuman/KorAlbert#2]
안녕하세요? albert를 공부 중인 학생입니다
올려주신 모델을 사용해보려고 했는데 vocab list가 빠져있어서요 혹시 공유해주실 수 있을까요?ㅜ

그리고 학습하신 환경과 소요시간을 알려주시면 큰 도움이 될 것 같습니다.
감사합니다!

**Comment by MrBananaHuman** [comment]
안녕하세요!
vocab의 경우엔 albert_config 폴더에 들어가있습니다 :-)
학습은 구글 GCP에서 TPU v3.0을 사용했구요, 학습한지 시간이 좀 많이 지나서 정확히 기억은 안나지만, 대략 일주일정도 학습했던 것 같습니다 :-)

**Comment by favorite-name** [comment]
답변 감사드립니다 많은 도움이 되었습니다 :) !!
