### ISSUE TITLE
[문의] pretraining files 생성 관련

### ISSUE THREAD

**Issue by lalaim** [MrBananaHuman/KorAlbert#4]
안녕하세요, 

언급하신 데이터 corpus로 pretraining files 만들때 학습과 동일한 환경에서 돌리셨는지, 소요시간은 얼마나 걸리셨는지 문의 드립니다!
제가 Google Colab Pro로 돌렸을때는 너무 오래걸릴뿐더러 자꾸 RAM이 부족해서 튕기는 현상이 나타나서요 ㅠㅠ
관련해서 advise 주시면 감사하겠습니다. 

좋은 하루 보내세요~!

**Comment by MrBananaHuman** [comment]
안녕하세요! 

학습의 경우엔 GCP와 TPU v3.0을 사용하였구요,
pretraining file은 
cpu: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
memory: 128기가
짜리 서버를 사용해서 만들었습니다. :-)
